name: Update market_ohlcv.db

# 수동 실행, 또는 매일 00:00 KST (UTC 15:00)에 스케줄 실행
on:
  schedule:
    - cron: '0 15 * * *'
  workflow_dispatch:

jobs:
  update-db:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드를 체크아웃 (persist-credentials: true 로 푸시 권한 유지)
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0

      # 2. Python 설정
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # 3. 의존성 설치
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # 4. DB 업데이트 스크립트 실행
      - name: Run stock_data.py to update DB
        run: python stock_data.py

      # 5. 변경된 DB 파일 커밋 & 푸시
      - name: Commit and push updated DB
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "자동 업데이트: market_ohlcv.db"
          add: "market_ohlcv.db"
          push: true
